name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies from the root folder
      # Yeh step pass ho jayega kyunke requirements.txt ab root mein hai
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Model training script ko sub-folder mein ja kar run karna
      # Humne yahan 'working-directory' add kiya hai
      - name: Test model training script
        working-directory: ./SolarProject
        run: python train_model.py
      
      # Step 5: Streamlit app ko bhi sub-folder mein ja kar check karna
      - name: Healthcheck Streamlit app
        working-directory: ./SolarProject
        run: streamlit run app.py -- --help
